version: '3.2'
services:
  app:
    build: .
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "3000:3000" # localhost:3000にポートをマッピングする
